name: 提出 API 变动
title: "API Changed: "
description: API、事件、返回模型等发生变动
labels: ["✨feature"]
body:
  - type: input
    id: api
    attributes:
      label: 变化部分
      description: 变化的 API、事件或 API 返回模型
    validations:
      required: true

  - type: input
    id: docs
    attributes:
      label: 文档地址
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 详细描述
