"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RoomType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RoomTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RoomType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RoomTypeInvalid: _RoomType.ValueType  # 0
    RoomTypeChatRoom: _RoomType.ValueType  # 1
    """聊天房间"""
    RoomTypePostRoom: _RoomType.ValueType  # 2
    """帖子房间"""
    RoomTypeSceneRoom: _RoomType.ValueType  # 3
    """场景房间"""

class RoomType(_RoomType, metaclass=_RoomTypeEnumTypeWrapper): ...

RoomTypeInvalid: RoomType.ValueType  # 0
RoomTypeChatRoom: RoomType.ValueType  # 1
"""聊天房间"""
RoomTypePostRoom: RoomType.ValueType  # 2
"""帖子房间"""
RoomTypeSceneRoom: RoomType.ValueType  # 3
"""场景房间"""
global___RoomType = RoomType

class _ObjectName:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ObjectNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ObjectName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknowObjectName: _ObjectName.ValueType  # 0
    Text: _ObjectName.ValueType  # 1
    """文本消息"""
    Post: _ObjectName.ValueType  # 2
    """帖子消息"""

class ObjectName(_ObjectName, metaclass=_ObjectNameEnumTypeWrapper): ...

UnknowObjectName: ObjectName.ValueType  # 0
Text: ObjectName.ValueType  # 1
"""文本消息"""
Post: ObjectName.ValueType  # 2
"""帖子消息"""
global___ObjectName = ObjectName

@typing_extensions.final
class RobotTemplate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Param(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DESC_FIELD_NUMBER: builtins.int
        desc: builtins.str
        """参数描述"""
        def __init__(
            self,
            *,
            desc: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["desc", b"desc"]) -> None: ...

    @typing_extensions.final
    class Command(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        DESC_FIELD_NUMBER: builtins.int
        PARAMS_FIELD_NUMBER: builtins.int
        name: builtins.str
        """指令名称"""
        desc: builtins.str
        """指令描述"""
        @property
        def params(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RobotTemplate.Param]:
            """指令参数"""
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            desc: builtins.str = ...,
            params: collections.abc.Iterable[global___RobotTemplate.Param] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["desc", b"desc", "name", b"name", "params", b"params"]) -> None: ...

    @typing_extensions.final
    class CustomSetting(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        URL_FIELD_NUMBER: builtins.int
        name: builtins.str
        """自定义设置项名称"""
        url: builtins.str
        """自定义设置项页面"""
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            url: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "url", b"url"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    ICON_FIELD_NUMBER: builtins.int
    COMMANDS_FIELD_NUMBER: builtins.int
    CUSTOM_SETTINGS_FIELD_NUMBER: builtins.int
    IS_ALLOWED_ADD_TO_OTHER_VILLA_FIELD_NUMBER: builtins.int
    id: builtins.str
    """机器人模板 id"""
    name: builtins.str
    """机器人名称"""
    desc: builtins.str
    """机器人描述"""
    icon: builtins.str
    """机器人 icon"""
    @property
    def commands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RobotTemplate.Command]:
        """指令列表"""
    @property
    def custom_settings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RobotTemplate.CustomSetting]:
        """自定义设置项"""
    is_allowed_add_to_other_villa: builtins.bool
    """是否允许添加到其他大别野"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        desc: builtins.str = ...,
        icon: builtins.str = ...,
        commands: collections.abc.Iterable[global___RobotTemplate.Command] | None = ...,
        custom_settings: collections.abc.Iterable[global___RobotTemplate.CustomSetting] | None = ...,
        is_allowed_add_to_other_villa: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["commands", b"commands", "custom_settings", b"custom_settings", "desc", b"desc", "icon", b"icon", "id", b"id", "is_allowed_add_to_other_villa", b"is_allowed_add_to_other_villa", "name", b"name"]) -> None: ...

global___RobotTemplate = RobotTemplate

@typing_extensions.final
class Robot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEMPLATE_FIELD_NUMBER: builtins.int
    VILLA_ID_FIELD_NUMBER: builtins.int
    @property
    def template(self) -> global___RobotTemplate:
        """所属机器人模板"""
    villa_id: builtins.int
    """大别野 id"""
    def __init__(
        self,
        *,
        template: global___RobotTemplate | None = ...,
        villa_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["template", b"template"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["template", b"template", "villa_id", b"villa_id"]) -> None: ...

global___Robot = Robot

@typing_extensions.final
class QuoteMessageInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    MSG_UID_FIELD_NUMBER: builtins.int
    SEND_AT_FIELD_NUMBER: builtins.int
    MSG_TYPE_FIELD_NUMBER: builtins.int
    BOT_MSG_ID_FIELD_NUMBER: builtins.int
    FROM_USER_ID_FIELD_NUMBER: builtins.int
    FROM_USER_ID_STR_FIELD_NUMBER: builtins.int
    FROM_USER_NICKNAME_FIELD_NUMBER: builtins.int
    content: builtins.str
    """消息内容"""
    msg_uid: builtins.str
    """消息msg_uid"""
    send_at: builtins.int
    msg_type: builtins.str
    """消息类型"""
    bot_msg_id: builtins.str
    """如果是机器人消息，则该字段不为空字符串"""
    from_user_id: builtins.int
    """发送者id"""
    from_user_id_str: builtins.str
    """发送者id（string）"""
    from_user_nickname: builtins.str
    """发送者昵称"""
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        msg_uid: builtins.str = ...,
        send_at: builtins.int = ...,
        msg_type: builtins.str = ...,
        bot_msg_id: builtins.str = ...,
        from_user_id: builtins.int = ...,
        from_user_id_str: builtins.str = ...,
        from_user_nickname: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bot_msg_id", b"bot_msg_id", "content", b"content", "from_user_id", b"from_user_id", "from_user_id_str", b"from_user_id_str", "from_user_nickname", b"from_user_nickname", "msg_type", b"msg_type", "msg_uid", b"msg_uid", "send_at", b"send_at"]) -> None: ...

global___QuoteMessageInfo = QuoteMessageInfo

@typing_extensions.final
class RobotEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EventType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RobotEvent._EventType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UnknowRobotEventType: RobotEvent._EventType.ValueType  # 0
        JoinVilla: RobotEvent._EventType.ValueType  # 1
        """加入大别野"""
        SendMessage: RobotEvent._EventType.ValueType  # 2
        """发送消息"""
        CreateRobot: RobotEvent._EventType.ValueType  # 3
        """大别野添加机器人实例"""
        DeleteRobot: RobotEvent._EventType.ValueType  # 4
        """大别野删除机器人实例"""
        AddQuickEmoticon: RobotEvent._EventType.ValueType  # 5
        """表情表态"""
        AuditCallback: RobotEvent._EventType.ValueType  # 6
        """审核结果回调"""
        ClickMsgComponent: RobotEvent._EventType.ValueType  # 7
        """点击消息组件"""

    class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...
    UnknowRobotEventType: RobotEvent.EventType.ValueType  # 0
    JoinVilla: RobotEvent.EventType.ValueType  # 1
    """加入大别野"""
    SendMessage: RobotEvent.EventType.ValueType  # 2
    """发送消息"""
    CreateRobot: RobotEvent.EventType.ValueType  # 3
    """大别野添加机器人实例"""
    DeleteRobot: RobotEvent.EventType.ValueType  # 4
    """大别野删除机器人实例"""
    AddQuickEmoticon: RobotEvent.EventType.ValueType  # 5
    """表情表态"""
    AuditCallback: RobotEvent.EventType.ValueType  # 6
    """审核结果回调"""
    ClickMsgComponent: RobotEvent.EventType.ValueType  # 7
    """点击消息组件"""

    @typing_extensions.final
    class ExtendData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class JoinVillaInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            JOIN_UID_FIELD_NUMBER: builtins.int
            JOIN_USER_NICKNAME_FIELD_NUMBER: builtins.int
            JOIN_AT_FIELD_NUMBER: builtins.int
            VILLA_ID_FIELD_NUMBER: builtins.int
            join_uid: builtins.int
            """加入用户 uid"""
            join_user_nickname: builtins.str
            """加入用户昵称"""
            join_at: builtins.int
            """加入时间 [待废弃, 可以改用 RobotEvent.created_at]"""
            villa_id: builtins.int
            """大别野 id"""
            def __init__(
                self,
                *,
                join_uid: builtins.int = ...,
                join_user_nickname: builtins.str = ...,
                join_at: builtins.int = ...,
                villa_id: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["join_at", b"join_at", "join_uid", b"join_uid", "join_user_nickname", b"join_user_nickname", "villa_id", b"villa_id"]) -> None: ...

        @typing_extensions.final
        class SendMessageInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            CONTENT_FIELD_NUMBER: builtins.int
            FROM_USER_ID_FIELD_NUMBER: builtins.int
            SEND_AT_FIELD_NUMBER: builtins.int
            OBJECT_NAME_FIELD_NUMBER: builtins.int
            ROOM_ID_FIELD_NUMBER: builtins.int
            NICKNAME_FIELD_NUMBER: builtins.int
            MSG_UID_FIELD_NUMBER: builtins.int
            BOT_MSG_ID_FIELD_NUMBER: builtins.int
            VILLA_ID_FIELD_NUMBER: builtins.int
            QUOTE_MSG_FIELD_NUMBER: builtins.int
            content: builtins.str
            """消息内容"""
            from_user_id: builtins.int
            """发送人 uid"""
            send_at: builtins.int
            """发送时间 [待废弃, 可以改用 RobotEvent.created_at]"""
            object_name: global___ObjectName.ValueType
            """消息类型"""
            room_id: builtins.int
            """房间 id"""
            nickname: builtins.str
            """昵称"""
            msg_uid: builtins.str
            """消息 id"""
            bot_msg_id: builtins.str
            """如果被回复的消息从属于机器人，则该字段不为空字符串"""
            villa_id: builtins.int
            """大别野 id"""
            @property
            def quote_msg(self) -> global___QuoteMessageInfo:
                """引用消息的内容"""
            def __init__(
                self,
                *,
                content: builtins.str = ...,
                from_user_id: builtins.int = ...,
                send_at: builtins.int = ...,
                object_name: global___ObjectName.ValueType = ...,
                room_id: builtins.int = ...,
                nickname: builtins.str = ...,
                msg_uid: builtins.str = ...,
                bot_msg_id: builtins.str = ...,
                villa_id: builtins.int = ...,
                quote_msg: global___QuoteMessageInfo | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["quote_msg", b"quote_msg"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["bot_msg_id", b"bot_msg_id", "content", b"content", "from_user_id", b"from_user_id", "msg_uid", b"msg_uid", "nickname", b"nickname", "object_name", b"object_name", "quote_msg", b"quote_msg", "room_id", b"room_id", "send_at", b"send_at", "villa_id", b"villa_id"]) -> None: ...

        @typing_extensions.final
        class CreateRobotInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            VILLA_ID_FIELD_NUMBER: builtins.int
            villa_id: builtins.int
            """创建机器人实例的大别野 id"""
            def __init__(
                self,
                *,
                villa_id: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["villa_id", b"villa_id"]) -> None: ...

        @typing_extensions.final
        class DeleteRobotInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            VILLA_ID_FIELD_NUMBER: builtins.int
            villa_id: builtins.int
            def __init__(
                self,
                *,
                villa_id: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["villa_id", b"villa_id"]) -> None: ...

        @typing_extensions.final
        class AddQuickEmoticonInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            VILLA_ID_FIELD_NUMBER: builtins.int
            ROOM_ID_FIELD_NUMBER: builtins.int
            UID_FIELD_NUMBER: builtins.int
            EMOTICON_ID_FIELD_NUMBER: builtins.int
            EMOTICON_FIELD_NUMBER: builtins.int
            MSG_UID_FIELD_NUMBER: builtins.int
            IS_CANCEL_FIELD_NUMBER: builtins.int
            BOT_MSG_ID_FIELD_NUMBER: builtins.int
            EMOTICON_TYPE_FIELD_NUMBER: builtins.int
            villa_id: builtins.int
            """大别野 id"""
            room_id: builtins.int
            """房间 id"""
            uid: builtins.int
            """回复用户 id"""
            emoticon_id: builtins.int
            """表情 id"""
            emoticon: builtins.str
            """表情"""
            msg_uid: builtins.str
            """消息 id"""
            is_cancel: builtins.bool
            """是否是取消表情"""
            bot_msg_id: builtins.str
            """如果被回复的消息从属于机器人，则该字段不为空字符串"""
            emoticon_type: builtins.int
            """表情类型"""
            def __init__(
                self,
                *,
                villa_id: builtins.int = ...,
                room_id: builtins.int = ...,
                uid: builtins.int = ...,
                emoticon_id: builtins.int = ...,
                emoticon: builtins.str = ...,
                msg_uid: builtins.str = ...,
                is_cancel: builtins.bool = ...,
                bot_msg_id: builtins.str = ...,
                emoticon_type: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["bot_msg_id", b"bot_msg_id", "emoticon", b"emoticon", "emoticon_id", b"emoticon_id", "emoticon_type", b"emoticon_type", "is_cancel", b"is_cancel", "msg_uid", b"msg_uid", "room_id", b"room_id", "uid", b"uid", "villa_id", b"villa_id"]) -> None: ...

        @typing_extensions.final
        class AuditCallbackInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _AuditResult:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _AuditResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RobotEvent.ExtendData.AuditCallbackInfo._AuditResult.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                Pass: RobotEvent.ExtendData.AuditCallbackInfo._AuditResult.ValueType  # 1
                Reject: RobotEvent.ExtendData.AuditCallbackInfo._AuditResult.ValueType  # 2

            class AuditResult(_AuditResult, metaclass=_AuditResultEnumTypeWrapper): ...
            Pass: RobotEvent.ExtendData.AuditCallbackInfo.AuditResult.ValueType  # 1
            Reject: RobotEvent.ExtendData.AuditCallbackInfo.AuditResult.ValueType  # 2

            AUDIT_ID_FIELD_NUMBER: builtins.int
            BOT_TPL_ID_FIELD_NUMBER: builtins.int
            VILLA_ID_FIELD_NUMBER: builtins.int
            ROOM_ID_FIELD_NUMBER: builtins.int
            USER_ID_FIELD_NUMBER: builtins.int
            PASS_THROUGH_FIELD_NUMBER: builtins.int
            AUDIT_RESULT_FIELD_NUMBER: builtins.int
            audit_id: builtins.str
            """机器人平台审核事件 id"""
            bot_tpl_id: builtins.str
            """机器人 id"""
            villa_id: builtins.int
            """大别野 id"""
            room_id: builtins.int
            """房间 id"""
            user_id: builtins.int
            """用户 id"""
            pass_through: builtins.str
            """透传字段"""
            audit_result: global___RobotEvent.ExtendData.AuditCallbackInfo.AuditResult.ValueType
            """审核结果"""
            def __init__(
                self,
                *,
                audit_id: builtins.str = ...,
                bot_tpl_id: builtins.str = ...,
                villa_id: builtins.int = ...,
                room_id: builtins.int = ...,
                user_id: builtins.int = ...,
                pass_through: builtins.str = ...,
                audit_result: global___RobotEvent.ExtendData.AuditCallbackInfo.AuditResult.ValueType = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["audit_id", b"audit_id", "audit_result", b"audit_result", "bot_tpl_id", b"bot_tpl_id", "pass_through", b"pass_through", "room_id", b"room_id", "user_id", b"user_id", "villa_id", b"villa_id"]) -> None: ...

        @typing_extensions.final
        class ClickMsgComponentInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            VILLA_ID_FIELD_NUMBER: builtins.int
            ROOM_ID_FIELD_NUMBER: builtins.int
            COMPONENT_ID_FIELD_NUMBER: builtins.int
            MSG_UID_FIELD_NUMBER: builtins.int
            UID_FIELD_NUMBER: builtins.int
            BOT_MSG_ID_FIELD_NUMBER: builtins.int
            TEMPLATE_ID_FIELD_NUMBER: builtins.int
            EXTRA_FIELD_NUMBER: builtins.int
            villa_id: builtins.int
            room_id: builtins.int
            component_id: builtins.str
            """自定义组件id"""
            msg_uid: builtins.str
            uid: builtins.int
            bot_msg_id: builtins.str
            template_id: builtins.int
            """模板id"""
            extra: builtins.str
            """机器人自定义透传数据"""
            def __init__(
                self,
                *,
                villa_id: builtins.int = ...,
                room_id: builtins.int = ...,
                component_id: builtins.str = ...,
                msg_uid: builtins.str = ...,
                uid: builtins.int = ...,
                bot_msg_id: builtins.str = ...,
                template_id: builtins.int = ...,
                extra: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["bot_msg_id", b"bot_msg_id", "component_id", b"component_id", "extra", b"extra", "msg_uid", b"msg_uid", "room_id", b"room_id", "template_id", b"template_id", "uid", b"uid", "villa_id", b"villa_id"]) -> None: ...

        JOINVILLA_FIELD_NUMBER: builtins.int
        SENDMESSAGE_FIELD_NUMBER: builtins.int
        CREATEROBOT_FIELD_NUMBER: builtins.int
        DELECTROBOT_FIELD_NUMBER: builtins.int
        ADDQUICKEMOTION_FIELD_NUMBER: builtins.int
        AUDITCALLBACK_FIELD_NUMBER: builtins.int
        CLICKMSGCOMPONENT_FIELD_NUMBER: builtins.int
        @property
        def JoinVilla(self) -> global___RobotEvent.ExtendData.JoinVillaInfo:
            """加入大别野扩展信息"""
        @property
        def SendMessage(self) -> global___RobotEvent.ExtendData.SendMessageInfo:
            """发送消息扩展信息"""
        @property
        def CreateRobot(self) -> global___RobotEvent.ExtendData.CreateRobotInfo:
            """添加机器人扩展信息"""
        @property
        def DelectRobot(self) -> global___RobotEvent.ExtendData.DeleteRobotInfo:
            """删除机器人扩展信息"""
        @property
        def AddQuickEmotion(self) -> global___RobotEvent.ExtendData.AddQuickEmoticonInfo:
            """表情表态扩展信息"""
        @property
        def AuditCallback(self) -> global___RobotEvent.ExtendData.AuditCallbackInfo:
            """审核回调信息"""
        @property
        def ClickMsgComponent(self) -> global___RobotEvent.ExtendData.ClickMsgComponentInfo:
            """点击消息组件回传"""
        def __init__(
            self,
            *,
            JoinVilla: global___RobotEvent.ExtendData.JoinVillaInfo | None = ...,
            SendMessage: global___RobotEvent.ExtendData.SendMessageInfo | None = ...,
            CreateRobot: global___RobotEvent.ExtendData.CreateRobotInfo | None = ...,
            DelectRobot: global___RobotEvent.ExtendData.DeleteRobotInfo | None = ...,
            AddQuickEmotion: global___RobotEvent.ExtendData.AddQuickEmoticonInfo | None = ...,
            AuditCallback: global___RobotEvent.ExtendData.AuditCallbackInfo | None = ...,
            ClickMsgComponent: global___RobotEvent.ExtendData.ClickMsgComponentInfo | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["AddQuickEmotion", b"AddQuickEmotion", "AuditCallback", b"AuditCallback", "ClickMsgComponent", b"ClickMsgComponent", "CreateRobot", b"CreateRobot", "DelectRobot", b"DelectRobot", "EventData", b"EventData", "JoinVilla", b"JoinVilla", "SendMessage", b"SendMessage"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["AddQuickEmotion", b"AddQuickEmotion", "AuditCallback", b"AuditCallback", "ClickMsgComponent", b"ClickMsgComponent", "CreateRobot", b"CreateRobot", "DelectRobot", b"DelectRobot", "EventData", b"EventData", "JoinVilla", b"JoinVilla", "SendMessage", b"SendMessage"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["EventData", b"EventData"]) -> typing_extensions.Literal["JoinVilla", "SendMessage", "CreateRobot", "DelectRobot", "AddQuickEmotion", "AuditCallback", "ClickMsgComponent"] | None: ...

    ROBOT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    EXTEND_DATA_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    SEND_AT_FIELD_NUMBER: builtins.int
    @property
    def robot(self) -> global___Robot:
        """事件相关机器人"""
    type: global___RobotEvent.EventType.ValueType
    """事件类型"""
    @property
    def extend_data(self) -> global___RobotEvent.ExtendData:
        """事件拓展信息"""
    created_at: builtins.int
    """事件发生时间"""
    id: builtins.str
    """事件 id"""
    send_at: builtins.int
    """事件消息投递时间"""
    def __init__(
        self,
        *,
        robot: global___Robot | None = ...,
        type: global___RobotEvent.EventType.ValueType = ...,
        extend_data: global___RobotEvent.ExtendData | None = ...,
        created_at: builtins.int = ...,
        id: builtins.str = ...,
        send_at: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["extend_data", b"extend_data", "robot", b"robot"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "extend_data", b"extend_data", "id", b"id", "robot", b"robot", "send_at", b"send_at", "type", b"type"]) -> None: ...

global___RobotEvent = RobotEvent
