name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - run: |
          echo "TAG=v${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Bump version
        run: |
          sed -i "3c\__version__ = \"${{ env.VERSION }}\"" hertavilla/version.py

      - name: Push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m ":bookmark: Release ${{ env.VERSION }}"
          git tag ${{ env.TAG }}
          git push && git push --tags

      - name: Generate release changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc03
        id: changelog
        with:
          configuration: .github/release_configuration.json

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: true
          cache-dependency-path: ./pdm.lock

      - name: Install dependencies
        run: pdm sync
        shell: bash

      - name: Build and Publish package
        run: |
          pdm publish
          gh release create ${{ env.TAG }} --notes ${{steps.changelog.outputs.changelog}} -t ${{ env.TAG }} dist/*.tar.gz dist/*.whl
