name: Unittest

on:
  push:
  pull_request:


jobs:
  test:
    name: Test
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.version }}
          cache: true
          cache-dependency-path: ./pdm.lock

      - name: Install dependencies
        run: pdm install -G test
        shell: bash

      - name: Run Pytest
        run: |
          cd tests
          pdm run pytest
